name: HelloCheck

on:
  pull_request:
    branches: [automergetarget]
    paths:
      - "cmd/hello/**"

jobs:
  build:
    name: Hello Tests
    runs-on: ubuntu-latest
    steps:
      - name: Sample step
        shell: bash
        run: |
          sleep 10
          echo "running hello tests"
