name: Hello2Check

on:
  pull_request:
    branches: [automergetarget]
    paths:
      - "cmd/hello2/**"

jobs:
  build:
    name: Hello2 Tests
    runs-on: ubuntu-latest
    steps:
      - name: Sample step
        shell: bash
        run: |
          sleep 15
          echo "running hello2 tests"
